apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cronjob
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 10s" # Cron expression for once a day
  - name: timezone
    value: "UTC"    # Specify the timezone
  - name: route
    value: "generate-reports" # API route to call